# Generated by Django 5.1.5 on 2025-01-21 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='author_images/')),
            ],
            options={
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('publisher', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='book_images/')),
                ('description', models.TextField()),
                ('author', models.ManyToManyField(to='api.author')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.genre')),
            ],
        ),
    ]
